config/routes.rb
Rails.application.routes.draw do
	#pages static
	root 'static_pages#index'
	get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  #resources REST
	resources :gossips
  get '/welcome/:first_name', to: 'users#welcome', as: 'welcome'
  get 'profile/:user_id', to: 'users#profile', as: 'profile'
  #get '/gossip/:gossip_id', to: 'gossips#each_gossip', as: 'gossip'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user#, optional: true
	belongs_to :gossip#, optional: true
	belongs_to :commentable, polymorphic: true, optional: true
	has_many :comments, as: :commentable
	has_many :likes, as: :likeable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user#, optional: true
	has_many :join_table_gossip_tags
	has_many :tags, through: :join_table_gossip_tags
	has_many :comments
	has_many :likes, as: :likeable
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
	belongs_to :gossip
	belongs_to :tag
end

app/models/join_table_user_private_message.rb
class JoinTableUserPrivateMessage < ApplicationRecord
	belongs_to :recipient, class_name: "User"
	belongs_to :private_message
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :likeable, polymorphic: true
	belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"#, optional: true
	has_many :join_table_user_private_messages
	has_many :recipients, class_name: "User", through: :join_table_user_private_messages
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_table_gossip_tags
	has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :join_table_user_private_messages
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage", through: :join_table_user_private_messages
	has_many :comments
	has_many :likes
	validates :first_name, presence: true
	validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	def index
	end
  def each_gossip
  	@gossip = Gossip.find_by(id: params[:gossip_id])
  	@author = @gossip.user
  	@first_name = @author.first_name
  end
  def new
  	@gossip = Gossip.new
  end
  def create
  	@gossip = Gossip.new('title' => params[:title], 'content' => params[:content], 'user' => User.find(11))
  	if @gossip.save # essaie de sauvegarder en base @gossip
  	  # si ça marche, il redirige vers la page d'index du site
  	  redirect_to root_path
  	else
  	  # sinon, il render la view new (qui est celle sur laquelle on est déjà)
  	  render 'new'
  	end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end
  def contact
  end
  def index
  	@gossips = Gossip.all
  	@indicator_b = 0
  	@indicator_n = 0
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def welcome
  	@user = User.find_by(first_name: params[:first_name])
  	#puts "Ceci est mon premier user : #{@user}"
  	#puts params
  end
  def profile
  	@user = User.find_by(id: params[:user_id])
  	#puts "Ceci est mon premier user : #{@user}"
  	#puts params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/each_gossip.html.erb
<h1>Gossip n°<%= @gossip.id %></h1>
<p>Auteur.e : <%= @author.first_name %> | <%= link_to "clique ici", profile_path(@author.id) %> pour voir sa page</p>
<p>Titre : <%= @gossip.title %></p>
<p>Contenu : <%= @gossip.content %></p>
<p>Date : <%= @gossip.created_at %></p>

app/views/gossips/new.html.erb
<h1>Créer un Gossip !</h1>
<%= form_tag url_for(action: 'create'), method: "post" do %>
	<!--input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"-->
  <!--input type="text" name="gossip_text"-->
  <!--input type="submit" value="Valider"-->
  <%= label_tag 'Title' %>
  <%= text_field_tag 'title', @gossip.title %>
  <br /> <br />
  <%= label_tag 'Content' %>
  <%= text_area_tag 'content', @gossip.content %>
  <br /> <br />
  <%= submit_tag "Create Gossip" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/3.3/examples/cover/cover.css" rel="stylesheet">
    <!-- le font Montserrat de google -->
<!--link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" -->

  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "The Gossip Project", root_path, :class => "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, :class => "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "L-Quipe", team_path, :class => "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Ring My Bell", contact_path, :class => "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

    <div class="container">
      <%= yield %>
    </div><!-- /.container -->
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>#tél_à_cadran</h1>
<p>On se bigophone ?</p>
<p>Savais-tu que jusque 1997 les numéros de téléphone en France n'avaient que 8 chiffres ?</p>
<p>What a Crazy World</p>
<%= image_tag("https://media.giphy.com/media/6FoSsGSo6F7u8/giphy.gif") %>

app/views/static_pages/index.html.erb
<h1>The Gossip Project</h1>
<!--p>Bienvenue chez 'User', le site est en construction, peu de commérages pour le moment. Et si tu nous <a href="/gossips/new/">aidais à en créer un</a> ?</p -->

<!-- pour faire fonctionner le card-deck 3*3 on utilise un double indicator "indicator_b" et "indicator_n" pour filter les "i" des index des "gossip" qui nous intéressent -->
<% 20.times do %>
  <% @indicator_n += 1 %>
  <%if @indicator_n % 3 == 0%>
    <div class="card-deck">
    <% @gossips.each_with_index do |gossip, i| %>
    <%if (i >= @indicator_b) && (i < @indicator_n) %>
      <div class="card mt-4">
        <img class="card-img-top" src="https://media.giphy.com/media/2aJWos8PLvdI7pGj0E/giphy.gif" alt="Card image cap">
        <!--%= image_tag(".../100px180/"), :class => "card-img-top", :alt => "Card image cap" %-->
        <div class="card-body">
          <h5 class="card-title"><%= gossip.title %></h5>
          <p class="card-text">Pour en savoir plus, l'auteur de cette prose est : <%= gossip.user.first_name %></p>
          <%= link_to "Voir le gossip", gossip_path(gossip.id), :class => "btn btn-primary" %>
        </div>
      </div>
    <% end %>
    <% end %>
    </div>
    <% @indicator_b += 3 %>
  <% end %>
<% end %>
<!-- on affiche le reliquat si besoin -->
    <div class="card-deck">
    <% @gossips.each_with_index do |gossip, i| %>
    <%if i >= @indicator_b %>
      <div class="card mt-4 mb-4">
        <img class="card-img-top" src="https://media.giphy.com/media/2aJWos8PLvdI7pGj0E/giphy.gif" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%= gossip.title %></h5>
          <p class="card-text">Pour en savoir plus, l'auteur de cette prose est : <%= gossip.user.first_name %></p>
          <%= link_to "Voir le gossip", gossip_path(gossip.id), :class => "btn btn-primary" %>
        </div>
      </div>
    <% end %>
    <% end %>
    </div>

app/views/static_pages/team.html.erb
<h1>One Team</h1>
<p>Sky is the limit as Froomie says</p>
<%= image_tag("itchy-scratchy.png") %>

app/views/users/profile.html.erb
<h1>Page de : <%= @user.first_name %></h1>
<p>Identifiant Auteur.e : <%= @user.id %></p>
<p>Prénom : <%= @user.first_name %></p>
<p>Nom : <%= @user.last_name %></p>
<p>Ville : <%= @user.city.name %></p>

app/views/users/welcome.html.erb
<h1>Welcome <%= @user.first_name %></h1>
<p>Find me in app/views/users/welcome.html.erb</p>